name: hellow-world
on: push
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:        
      - name: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: scanning
        uses: gitleaks/gitleaks-action@v2
        
      - name: docker-image
        run: docker build -t rayeescore/cf-sysfoo .
        
      - name: docker-hub
        run: echo "Hellow World!"
        
      - name: dast
        run: echo "Hellow World!" 
        
